# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: sphero_pwn 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "sphero_pwn"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Victor Costan"]
  s.date = "2015-12-15"
  s.description = "This library is currently focused on reverse-engineering\n      the undocumented parts of Sphero"
  s.email = "victor@costan.us"
  s.executables = ["sphero_diagnostics.rb", "sphero_map_flash.rb", "sphero_save_flash_block.rb", "sphero_set_flag.rb", "sphero_soft_reboot.rb", "sphero_toggle_user_hack.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/sphero_diagnostics.rb",
    "bin/sphero_map_flash.rb",
    "bin/sphero_save_flash_block.rb",
    "bin/sphero_set_flag.rb",
    "bin/sphero_soft_reboot.rb",
    "bin/sphero_toggle_user_hack.rb",
    "lib/sphero_pwn.rb",
    "lib/sphero_pwn/async.rb",
    "lib/sphero_pwn/asyncs.rb",
    "lib/sphero_pwn/asyncs/flash_block.rb",
    "lib/sphero_pwn/asyncs/l1_diagnostics.rb",
    "lib/sphero_pwn/channel.rb",
    "lib/sphero_pwn/channel_recorder.rb",
    "lib/sphero_pwn/command.rb",
    "lib/sphero_pwn/commands.rb",
    "lib/sphero_pwn/commands/boot_main_app.rb",
    "lib/sphero_pwn/commands/enter_bootloader.rb",
    "lib/sphero_pwn/commands/get_device_mode.rb",
    "lib/sphero_pwn/commands/get_flash_block.rb",
    "lib/sphero_pwn/commands/get_permanent_flags.rb",
    "lib/sphero_pwn/commands/get_versions.rb",
    "lib/sphero_pwn/commands/is_page_blank.rb",
    "lib/sphero_pwn/commands/l1_diagnostics.rb",
    "lib/sphero_pwn/commands/l2_diagnostics.rb",
    "lib/sphero_pwn/commands/ping.rb",
    "lib/sphero_pwn/commands/set_device_mode.rb",
    "lib/sphero_pwn/commands/set_permanent_flags.rb",
    "lib/sphero_pwn/replay_channel.rb",
    "lib/sphero_pwn/response.rb",
    "lib/sphero_pwn/session.rb",
    "lib/sphero_pwn/test_channel.rb",
    "sphero_pwn.gemspec",
    "test/channel_recorder_test.rb",
    "test/command_test.rb",
    "test/commands/boot_main_app_test.rb",
    "test/commands/enter_bootloader_test.rb",
    "test/commands/get_device_mode_test.rb",
    "test/commands/get_flash_block_test.rb",
    "test/commands/get_permanent_flags_test.rb",
    "test/commands/get_versions_test.rb",
    "test/commands/is_page_blank_test.rb",
    "test/commands/l1_diagnostics_test.rb",
    "test/commands/l2_diagnostics_test.rb",
    "test/commands/ping_test.rb",
    "test/commands/set_device_mode_test.rb",
    "test/commands/set_permanent_flags_test.rb",
    "test/data/enter_bootloader.txt",
    "test/data/get_device_mode.txt",
    "test/data/get_factory_config.txt",
    "test/data/get_permanent_flags.txt",
    "test/data/get_soul.txt",
    "test/data/get_version.txt",
    "test/data/is_page_blank.txt",
    "test/data/l1_diagnostics.txt",
    "test/data/l2_diagnostics.txt",
    "test/data/ping.txt",
    "test/data/set_device_mode.txt",
    "test/data/set_permanent_flags.txt",
    "test/helper.rb",
    "test/replay_channel_test.rb",
    "test/response_test.rb",
    "test/session_test.rb",
    "test/sphero_pwn_test.rb"
  ]
  s.homepage = "http://github.com/pwnall/sphero_pwn"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Wrapper for Sphero's bluetooth protocol"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubyserial>, [">= 0.2.4"])
      s.add_development_dependency(%q<bundler>, [">= 1.3.5"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_development_dependency(%q<minitest>, [">= 5.8.3"])
      s.add_development_dependency(%q<mocha>, [">= 1.1.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0.8.7.6"])
    else
      s.add_dependency(%q<rubyserial>, [">= 0.2.4"])
      s.add_dependency(%q<bundler>, [">= 1.3.5"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_dependency(%q<minitest>, [">= 5.8.3"])
      s.add_dependency(%q<mocha>, [">= 1.1.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0.8.7.6"])
    end
  else
    s.add_dependency(%q<rubyserial>, [">= 0.2.4"])
    s.add_dependency(%q<bundler>, [">= 1.3.5"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    s.add_dependency(%q<minitest>, [">= 5.8.3"])
    s.add_dependency(%q<mocha>, [">= 1.1.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0.8.7.6"])
  end
end

