# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: sphero_pwn 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "sphero_pwn"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Victor Costan"]
  s.date = "2015-12-12"
  s.description = "This library is currently focused on reverse-engineering\n      the undocumented parts of Sphero"
  s.email = "victor@costan.us"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/sphero_pwn.rb",
    "lib/sphero_pwn/async.rb",
    "lib/sphero_pwn/asyncs.rb",
    "lib/sphero_pwn/asyncs/l1_diagnostics.rb",
    "lib/sphero_pwn/channel.rb",
    "lib/sphero_pwn/channel_recorder.rb",
    "lib/sphero_pwn/command.rb",
    "lib/sphero_pwn/commands.rb",
    "lib/sphero_pwn/commands/get_versions.rb",
    "lib/sphero_pwn/commands/l1_diagnostics.rb",
    "lib/sphero_pwn/commands/ping.rb",
    "lib/sphero_pwn/replay_channel.rb",
    "lib/sphero_pwn/response.rb",
    "lib/sphero_pwn/session.rb",
    "lib/sphero_pwn/test_channel.rb",
    "test/channel_recorder_test.rb",
    "test/command_test.rb",
    "test/commands/get_versions_test.rb",
    "test/commands/l1_diagnostics_test.rb",
    "test/commands/ping_test.rb",
    "test/data/get_version.txt",
    "test/data/l1_diagnostics.txt",
    "test/data/ping.txt",
    "test/helper.rb",
    "test/replay_channel_test.rb",
    "test/response_test.rb",
    "test/session_test.rb",
    "test/sphero_pwn_test.rb"
  ]
  s.homepage = "http://github.com/pwnall/sphero_pwn"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Wrapper for Sphero's bluetooth protocol"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubyserial>, [">= 0.2.4"])
      s.add_development_dependency(%q<bundler>, [">= 1.3.5"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_development_dependency(%q<minitest>, [">= 5.8.3"])
      s.add_development_dependency(%q<mocha>, [">= 1.1.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0.8.7.6"])
    else
      s.add_dependency(%q<rubyserial>, [">= 0.2.4"])
      s.add_dependency(%q<bundler>, [">= 1.3.5"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_dependency(%q<minitest>, [">= 5.8.3"])
      s.add_dependency(%q<mocha>, [">= 1.1.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0.8.7.6"])
    end
  else
    s.add_dependency(%q<rubyserial>, [">= 0.2.4"])
    s.add_dependency(%q<bundler>, [">= 1.3.5"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    s.add_dependency(%q<minitest>, [">= 5.8.3"])
    s.add_dependency(%q<mocha>, [">= 1.1.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0.8.7.6"])
  end
end

